[package]
name = "backdrop-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
unsplash-api = { path = "../unsplash-api" }
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
http = "1.3.1"
keyring = { version = "3.6.3", features = ["apple-native", "linux-native", "windows-native"] }
reqwest = { version = "0.12.24", features = ["json"] }
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
url = "2.5.7"
webbrowser = "1.0.6"
